comments/urls.py
from django.urls import path
from . import views

app_name = "comments"

urlpatterns = [
    path("<pk>/delete", views.delete, name="delete"),
    path("<pk>/position", views.position, name="position"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("pages.urls")),
    path("nannies/", include("nannies.urls")),
    path("comments/", include("comments.urls")),
    path("api/v1/comments/", include("comments.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("hello_kitty/", admin.site.urls),
]

nannies/urls.py
from django.urls import path
from . import views as nanny_views
from comments import views as comment_views
from .views import NewView, IndexView, ShowView, NannyDeleteView

app_name = "nannies"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("new", NewView.as_view(), name="new"),
    path("add", nanny_views.create, name="add"),
    path("<id>/edit", nanny_views.edit, name="edit"),
    path("<pk>/delete", NannyDeleteView.as_view(), name="delete"),
    path("<pk>/comment", comment_views.create, name="comment"),
    path("<pk>", ShowView.as_view(), name="show"),
]

pages/urls.py
from django.urls import path
from .views import HomeView, AboutUsView, user_list

urlpatterns = [
    path("", HomeView.as_view(), name="root"),
    path("about", AboutUsView.as_view(), name="about"),
    path("api/user_list", user_list),
]

comments/models.py
from django.db import models
from nannies.models import Nanny
from django.utils import timezone
from positions.fields import PositionField


class CommentManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted_at=None)


class Comment(models.Model):
    nanny = models.ForeignKey(
        Nanny,
        on_delete=models.CASCADE,
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True)
    position = PositionField(collection='nanny')

    objects = CommentManager()

    def delete(self):
        self.deleted_at = timezone.now()
        self.save()

nannies/models.py
from django.db import models
from django.utils import timezone


GENDER_OPTIONS = [
    ("M", "男"),
    ("F", "女"),
    ("O", "其它"),
]


class NannyManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted_at=None)


class Nanny(models.Model):
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_OPTIONS)
    tel = models.CharField(max_length=20)
    nickname = models.CharField(max_length=100)
    description = models.TextField(default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True)

    objects = NannyManager()

    def __str__(self):
        gender_str = "Mr." if self.gender == "M" else "Mrs."
        return f"{gender_str} {self.name}"

    def delete(self):
        self.deleted_at = timezone.now()
        self.save()

comments/forms.py
from django import forms
from django.forms import ModelForm, widgets
from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
        labels = {"content": "留言內容"}
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "rows": 2,
                    "class": "textarea textarea-bordered",
                    "x-model": "content",
                }
            )
        }

nannies/forms.py
from django import forms
from django.forms import widgets
from .models import Nanny


class NannyForm(forms.ModelForm):
    class Meta:
        model = Nanny
        fields = ["name", "gender", "tel", "nickname", "description"]
        labels = {
            "name": "姓名",
            "gender": "性別",
            "tel": "電話",
            "nickname": "暱稱",
            "description": "簡介",
        }
        widgets = {
            "name": forms.TextInput(
                attrs={"class": "input input-bordered"},
            ),
            "tel": forms.TextInput(
                attrs={"class": "input input-bordered"},
            ),
            "gender": forms.Select(
                attrs={"class": "select select-bordered"},
            ),
            "nickname": forms.TextInput(
                attrs={"class": "input input-bordered"},
            ),
            "description": forms.Textarea(
                attrs={"class": "textarea textarea-bordered"},
            ),
        }

comments/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_http_methods
from nannies.models import Nanny
from .forms import CommentForm
from .models import Comment
from django.http import HttpResponse, QueryDict, JsonResponse


@require_POST
def delete(req, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return HttpResponse("")


@require_POST
def create(req, pk):
    nanny = get_object_or_404(Nanny, pk=pk)

    form = CommentForm(req.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.nanny = nanny
        comment.save()

        # return redirect("nannies:show", pk=nanny.id)
        return render(req, "comments/comment.html", {"comment": comment})
    
@require_http_methods(["PATCH"])
def position(req, pk):
    comment = get_object_or_404(Comment, pk=pk)
    new_index = int(QueryDict(req.body)["newIndex"])
    comment.position = new_index
    comment.save()
    return JsonResponse({"status": "success", "newIndex": new_index})
    

nannies/views.py
from django.shortcuts import HttpResponse, render, redirect, get_object_or_404
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.views.decorators.http import require_POST
from .models import Nanny
from .forms import NannyForm
from comments.forms import CommentForm
from django.views.generic import FormView, ListView, DetailView, DeleteView


class IndexView(ListView):
    model = Nanny

    def get_queryset(self):
        queryset = super().get_queryset()
        keyword = self.request.GET.get("keyword", "").strip()

        return queryset.filter(name__icontains=keyword)


class ShowView(DetailView):
    model = Nanny
    extra_context = {"comment_form": CommentForm()}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = self.object.comment_set.all().order_by("position")
        return context

    def post(self, request, pk):
        nanny = self.get_object()
        form = NannyForm(request.POST, instance=nanny)

        if form.is_valid():
            form.save()
            messages.success(request, "更新成功")

        return redirect("nannies:show", pk=nanny.id)


class NewView(FormView):
    form_class = NannyForm
    template_name = "nannies/new.html"


def edit(request, id):
    nanny = get_object_or_404(Nanny, pk=id)

    form = NannyForm(instance=nanny)

    return render(request, "nannies/edit.html", {"nanny": nanny, "form": form})


@require_POST
def create(request):
    form = NannyForm(request.POST)

    if form.is_valid():
        form.save()
        messages.success(request, "新增成功")

    return redirect("nannies:index")


class NannyDeleteView(DeleteView):
    model = Nanny

    def get_success_url(self):
        messages.success(self.request, "已刪除")
        return reverse("nannies:index")

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from nannies.models import Nanny


class HomeView(TemplateView):
    template_name = "pages/home.html"


class AboutUsView(TemplateView):
    template_name = "pages/about.html"


def user_list(request):
    nannies = Nanny.objects.all()
    return render(request, "pages/user_list.html", {"nannies": nannies})

templates/comments/comment.html
<div
  class="comment-item my-2 border-b py-2"
  data-id="{{ comment.id }}"
  data-csrf="{{ csrf_token }}"
>
  <form
    hx-confirm="確認刪除？"
    hx-swap="outerHTML swap:1s"
    hx-target="closest div"
    hx-post="{% url 'comments:delete' comment.id %}"
  >
    {% csrf_token %}
    <article>{{ comment.content }}</article>
    <time class="text-slate-400 text-sm"
      >{{ comment.created_at|date:'Y.m.d' }}</time
    >
    <button class="btn btn-xs btn-primary">刪除</button>
  </form>
</div>

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-theme="lofi">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}寵物保姆{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <script src="{% static 'scripts/app.js' %}" type="module"></script>
  </head>
  <body class="container mx-auto">
      {% include "shared/navbar.html" %}
      {% include "shared/message.html" %}

      <main class="my-2">
        {% block content %}{% endblock %}
      </main>

      {% include "shared/footer.html" %}
  </body>
</html>

templates/nannies/edit.html
{% extends 'layouts/base.html' %}

{% block content %}
    <h1 class="text-3xl my-2">更新保姆</h1>
    <form action="{% url 'nannies:show' nanny.id %}" method="post" class="flex flex-col gap-2">
        {% csrf_token %}

        {{ form.as_div }}

        <div>
            <input type="submit" value="更新" class="btn btn-primary">
        </div>
    </form>
{% endblock %}

templates/nannies/index.html
{% extends 'layouts/base.html' %}

{% block content %}
    <form>
        搜尋 <input type="search" name="keyword" class="px-2 py-1 border-2 border-gray-500">
        <button class="bg-gray-300 px-2 py-1">搜尋</button>
    </form>

    <h1>保姆列表</h1>
    <a class="bg-green-300 px-2 py-1 rounded-full" href="{% url 'nannies:new' %}">新增</a>

    {% for nanny in nannies %}
      <div>
          <a href="{% url 'nannies:show' nanny.id %}">{{ nanny.name }}</a>
      </div>
    {% endfor %}

{% endblock %}

templates/nannies/nanny_detail.html
{% extends 'layouts/base.html' %}

{% block content %}
  <section class="grid grid-cols-6 gap-2">
      <div class="col-span-4 my-2 pr-2">
          <h2 class="text-3xl">{{ nanny.name }}</h2>
          <article class="flex flex-col gap-4">
              {{ nanny.description|linebreaks }}
          </article>
          <section class="gap-2 my-2 flex">
              <a class="btn btn-sm btn-neutral" href="{% url 'nannies:edit' nanny.id %}">編輯</a>

              <form action="{% url 'nannies:delete' nanny.id %}"
                    method="post">
                  {% csrf_token %}
                  <button class="btn btn-sm btn-neutral">刪除</button>
              </form>
          </section>

          <aside class="col-span-2">
              <section class="my-2">
                  <form
                      x-data="{content: ''}"
                      x-ref="comment_form"
                      hx-swap="afterbegin"
                      hx-target="#comments"
                      hx-confirm="確認留言？"
                      hx-post="{% url 'nannies:comment' nanny.id %}"
                      @htmx:after-swap.window="$refs.comment_form.reset()">

                      {% csrf_token %}

                      <div class="flex flex-col gap-2">
                        {% for f in comment_form %}
                            <label class="text-lg">留言</label>
                            {{ f }}
                        {% endfor %}
                        <div>
                            <button x-bind:disabled="content.trim().length == 0" class="btn btn-sm btn-neutral">留言</button>
                        </div>
                      </div>

                  </form>
              </section>

              <section x-data="sortList" class="my-2">
                  {% for comment in comments %}
                    {% include "comments/comment.html" %}
                  {% endfor %}
              </section>
          </aside>
      </div>

      <div class="my-2">
          <h2 class="text-3xl">推薦</h2>
      </div>
  </section>

{% endblock %}

templates/nannies/nanny_list.html
{% extends 'layouts/base.html' %}

{% block content %}
    <form class="my-4">
        搜尋
        <input type="search" name="keyword" class="input input-bordered">
        <button class="btn btn-neutral">搜尋</button>
    </form>

    <h1 class="text-3xl my-2">保姆列表</h1>
    <a class="btn btn-neutral btn-sm" href="{% url 'nannies:new' %}">新增</a>

    <ul class="my-4 grid grid-cols-4 gap-4">
        {% for nanny in nanny_list %}
            <li class="flex flex-col gap-2 col-span-1 border rounded-sm p-3 border-slate-400">
                <a class="text-xl" href="{% url 'nannies:show' nanny.id %}">{{ nanny.name }}</a>
                <article>
                    {{ nanny.description|truncatewords:20 }}
                </article>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/nannies/new.html
{% extends 'layouts/base.html' %}

{% block content %}
    <h1 class="text-3xl my-2">新增保姆</h1>
    <form action="{% url 'nannies:add' %}" method="post" class="flex flex-col gap-2">
        {% csrf_token %}

        {{ form.as_div }}

        <div>
            <input type="submit" value="新增" class="btn btn-neutral">
        </div>
    </form>
{% endblock %}

templates/nannies/show.html
{% extends 'layouts/base.html' %}

{% block content %}
  <h2 class="text-2xl">{{ nanny.name }}</h2>
  <p>
      {{ nanny.description }}
  </p>
  <a href="{% url 'nannies:edit' nanny.id %}">編輯</a>

  <form action="{% url 'nannies:delete' nanny.id %}"
        method="post">
      {% csrf_token %}
      <button>刪除</button>
  </form>

{% endblock %}

templates/pages/about.html
{% extends "layouts/base.html" %}

{% block content %}
    <h1 class="text-3xl my-2">關於我們</h1>
    <article class="flex flex-col gap-2">
        <p>
            Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Etiam porta sem malesuada magna mollis euismod. Vestibulum id ligula porta felis euismod semper. Maecenas sed diam eget risus varius blandit sit amet non magna. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.
        </p>

        <p>
            Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec id elit non mi porta gravida at eget metus. Nulla vitae elit libero, a pharetra augue. Nullam quis risus eget urna mollis ornare vel eu leo.
        </p>

        <p>
            Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Nullam quis risus eget urna mollis ornare vel eu leo. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Nullam quis risus eget urna mollis ornare vel eu leo.
        </p>

        <p>
            Cras mattis consectetur purus sit amet fermentum. Nulla vitae elit libero, a pharetra augue. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Sed posuere consectetur est at lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam quis risus eget urna mollis ornare vel eu leo.
        </p>
    </article>
{% endblock %}

templates/pages/home.html
{% extends "layouts/base.html" %}

{% block content %}
    <h1 class="text-4xl">首頁</h1>
    <button hx-get="/api/user_list" hx-target="#my_target" class="px-2 py-1 bg-pink-400">click</button>

    <div id="my_target"></div>
{% endblock %}

templates/pages/user_list.html
<div x-data="{show: true}" x-show="show">
    <button @click="show = false">close</button>
    <ul>
        {% for nanny in nannies %}
            <li class="text-2xl">{{ nanny }}</li>
        {% endfor %}
    </ul>
</div>

templates/shared/footer.html
<footer class="border-t py-4 text-center">
    &copy; 寵物保姆 PetNanny
</footer>

templates/shared/message.html
{% if messages %}
    <div class="flash" x-show="show" x-data="flash_message">
        {% for message in messages %}
            <p class="{{ message.tags }} px-4 py-2 flex justify-between">
                <span>{{ message }}</span>
                <button @click="close">X</button>
            </p>
        {% endfor %}
    </div>
{% endif %}

templates/shared/navbar.html
<nav class="py-4 border-b flex justify-between">
    <ul class="flex gap-4">
        <li><a class="nav-link" href="{% url 'root' %}">首頁</a></li>
        <li><a class="nav-link" href="{% url 'nannies:index' %}">保姆列表</a></li>
        <li><a class="nav-link" href="{% url 'about' %}">關於我們</a></li>
    </ul>

    <ul class="flex gap-4">
        {% if user.is_authenticated %}
            <li>
                <form
                    action="{% url 'logout' %}"
                    method="post">
                    {% csrf_token %}
                    <button class="nav-link" href="#">登出</button>
                </form>
            </li>
        {% else %}
            <li><a class="nav-link" href="{% url 'login' %}">登入</a></li>
            <li><a class="nav-link" href="#">註冊</a></li>
        {% endif %}
    </ul>
</nav>